[[headers]]
  for = "/thumbnails/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://salarial.pt, https://api.salarial.pt"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=31536000"
